\documentclass[12pt]{article}

\usepackage{geometry}                % See geometry.pdf to learn the layout options. There are lots.
\geometry{a4paper,
 total={170mm,257mm},
 left=20mm,
 right=20mm,
 top=20mm,
 bottom=40mm}                   % ... or a4paper or a5paper or ...
\geometry{landscape}                % Activate for for rotated page geometry
\usepackage[parfill]{parskip}    % Activate to begin paragraphs with an empty line rather than an indent
\usepackage{graphicx}
\usepackage{amssymb}
\usepackage{epstopdf}
\usepackage{float}
\usepackage{hyperref}
\usepackage{booktabs}
\usepackage{colortbl, xcolor}
\usepackage{array}
\usepackage[utf8]{inputenc}


\setlength{\columnsep}{1cm}
\usepackage[backend=bibtex, sorting=none, style=chicago-authordate]{biblatex}
\setlength\bibitemsep{\baselineskip}
\usepackage[british]{babel}
\usepackage[export]{adjustbox}
\usepackage{listings}
\usepackage{color}
\definecolor{codegreen}{rgb}{0,0.6,0}
\definecolor{codegray}{rgb}{0.5,0.5,0.5}
\definecolor{codepurple}{rgb}{0.58,0,0.82}
\definecolor{backcolour}{rgb}{0.95,0.95,0.92}
\lstdefinestyle{mystyle}{
    backgroundcolor=\color{backcolour},
    commentstyle=\color{codegreen},
    keywordstyle=\color{magenta},
    numberstyle=\tiny\color{codegray},
    stringstyle=\color{codepurple},
    basicstyle=\footnotesize,
    breakatwhitespace=false,
    breaklines=true,
    captionpos=b,
    keepspaces=true,
    numbers=left,
    numbersep=5pt,
    showspaces=false,
    showstringspaces=false,
    showtabs=false,
    tabsize=2
}



\newcolumntype{L}[1]{>{\raggedright\let\newline\\
    \arraybackslash\hspace{0pt}}m{#1}}
\newcolumntype{C}[1]{>{\centering\let\newline\\
    \arraybackslash\hspace{0pt}}m{#1}}
\newcolumntype{R}[1]{>{\raggedleft\let\newline\\
    \arraybackslash\hspace{0pt}}m{#1}}
\newcolumntype{P}[1]{>{\raggedright\tabularxbackslash}p{#1}}

%\usepackage{pdflscape}
 \usepackage{rotating}
  
\usepackage{textcomp}
\lstset{style=mystyle}


\hypersetup{%
  colorlinks=true,% hyperlinks will be coloured
  linkcolor=blue,% hyperlink text will be green
}
\DeclareGraphicsRule{.tif}{png}{.png}{`convert #1 `dirname #1`/`basename #1 .tif`.png}

%% LOGOS
\usepackage{fancyhdr}
%\setlength{\headheight}{1.5cm}
\addtolength{\headheight}{2cm} % make more space for the header
\pagestyle{fancyplain} % use fancy for all pages except chapter start
\lhead{\includegraphics[height=1.3cm, width=2cm]{../Images/nbislogo.png}} % left logo
\rhead{\includegraphics[height=1.3cm, width=4cm]{../Images/SciLifeLab-logo.jpg}} % right logo
\cfoot{}
\lfoot{ChIP-seq data analysis, Stockholm, 2018}
\renewcommand{\headrulewidth}{0pt} % remove rule below header

%% DEFINE TOOLS AND VARIABLES
\newcommand{\courseName}{ChIP-seq data analysis}
\newcommand{\courseLocation}{Stockholm}
\newcommand{\courseDate}{2018}
\newcommand{\courseLeaderA}{Olga Dethlefsen}
\newcommand{\courseEmailA}{olga.dethlefsen@nbis.se}
\newcommand{\courseLeaderB}{Agata Smialowska}
\newcommand{\courseEmailB}{agata.smialowska@nbis.se}



%% BEGIN DOCUMENT
%\date{}
\begin{document}

\pagestyle{fancy}

<<include=FALSE, echo=F>>=
library(knitr)
opts_chunk$set(
concordance=TRUE
)
@

%% TITLE PAGE
%\title{NBIS course: ChIP-seq data analysis}
%\subtitle{Participants list}
% \title{NBIS course participants list}
% \author{}
% %\maketitle
% \thispagestyle{fancy}
% 
% \vspace{2cm}
% \begin{center}
% \begin{tabular}{l r}
% Course name: & {\courseName} \\
% Date: & {\courseDate} \\
% Location: & {\courseLocation}  \\
% Course leaders: & \courseLeaderA \textless{\courseEmailA}\textgreater\\
% & \courseLeaderB  \textless{\courseEmailB}\textgreater
% \end{tabular}
% \end{center}

%% TABLE OF CONTENTS
\newpage
%\tableofcontents

%% SUPPORT REQUEST
%\newpage
<<Rsetup, echo=F, include=FALSE>>=
rm(list=ls())
library(xtable)
@


<<participantsList, echo=F, results='asis'>>=
file.csv <- "../Certificates/NBIS-ChIP-seq-participants-2018.csv"
data.csv <- read.csv(file.csv)
idx.final <- which(data.csv$Final==1)
data.final <- data.csv[idx.final,]

data.list <- data.frame(Name=data.final$First.Name, Surname=data.final$Last.Name, email=data.final$Official.e.mail.address)

# Sort 
o <- order(data.list$Name)
data.list <- data.list[o,]

# 
rws <- seq(1, (nrow(data.list)), by = 2)
col <- rep("\\rowcolor[gray]{0.95}", length(rws))

print(xtable(data.list, align=c("c", "l", "l", "r")), 
  booktabs = TRUE,
  add.to.row = list(pos = as.list(rws), command = col),
  include.rownames=FALSE
  )
@





\end{document}  

